<MyGrid>
    
    GridLayout:
        cols: 1
        size: root.width-100, root.height-100
        pos: 50, 50

        GridLayout:
            cols: 2

            Label:
                text: 'name: '
        
            TextInput:
                multiline: False
        
            Label:
                text: 'email: '

            TextInput:
                multiline: False

        Button:
            text:'submit'
        
        
    